id: P002907
initial_creation_type: ocr
source_metadata:
  id: bdr:W23635
  title: ས་སྐྱ་པའི་མཁས་པ་རྣམས་ཀྱི་གསུང་སྐོར།
  author: ''
  volumes:
    45c08f0a1fd24a2296ba9f76294440d8:
      image_group_id: I1KG13611
      title: ''
      volume_number: 5
      total_pages: 0
    50d719908fbd41c9a99f8fb08a94f8c4:
      image_group_id: I1KG13612
      title: ''
      volume_number: 6
      total_pages: 0
    9125dffa9a1e4caa9d448a5458b0cc19:
      image_group_id: I1KG13613
      title: ''
      volume_number: 7
      total_pages: 698
      base_file: v001.txt
    b5330543119447e4a36b0440989e91fe:
      image_group_id: I1KG13614
      title: ''
      volume_number: 8
      total_pages: 694
      base_file: v002.txt
    98aa57d08a1d4db3b4330de063d2e1de:
      image_group_id: I1KG13615
      title: ''
      volume_number: 9
      total_pages: 800
      base_file: v003.txt
    806993ea4a7d48598f8785f208fb3b44:
      image_group_id: I3593
      title: ''
      volume_number: 1
      total_pages: 658
      base_file: v004.txt
    1993ab68ca9049ddab507db231121896:
      image_group_id: I3594
      title: ''
      volume_number: 2
      total_pages: 692
      base_file: v005.txt
    cccafefd504c458ba1f7136103a4424f:
      image_group_id: I3595
      title: ''
      volume_number: 3
      total_pages: 572
      base_file: v006.txt
    4d05e5430da54a76800301c0c10133e8:
      image_group_id: I3596
      title: ''
      volume_number: 4
      total_pages: 560
      base_file: v007.txt
