id: I087B300F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:11:20+00:00'
last_modified: '2022-06-07T16:04:43.523326+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23635
  title: ས་སྐྱ་པའི་མཁས་པ་རྣམས་ཀྱི་གསུང་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    97C4:
      image_group_id: I3593
      title: ''
      total_pages: 658
      order: 1
      base_file: 97C4.txt
    AAAD:
      image_group_id: I3594
      title: ''
      total_pages: 692
      order: 2
      base_file: AAAD.txt
    7ABC:
      image_group_id: I3595
      title: ''
      total_pages: 572
      order: 3
      base_file: 7ABC.txt
    FC0D:
      image_group_id: I3596
      title: ''
      total_pages: 560
      order: 4
      base_file: FC0D.txt
    77F9:
      image_group_id: I1KG13611
      title: ''
      total_pages: 0
      order: 5
      base_file: 77F9.txt
    '2498':
      image_group_id: I1KG13612
      title: ''
      total_pages: 0
      order: 6
      base_file: 2498.txt
    4B4E:
      image_group_id: I1KG13613
      title: ''
      total_pages: 698
      order: 7
      base_file: 4B4E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
